src/AuthCentral/Areas/Admin/Controllers/ClientRedirectUriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.RegularExpressions;

using Microsoft.AspNet.Mvc;

using IdentityServer3.Core.Models;
using IdentityServer3.Core.Services;

using Fsw.Enterprise.AuthCentral.Areas.Admin.Models;
using Fsw.Enterprise.AuthCentral.MongoStore.Admin;
using Microsoft.AspNet.Authorization;

namespace Fsw.Enterprise.AuthCentral.Areas.Admin.Controllers
{
    [Authorize("FswAdmin")]
    [Area("Admin"), Route("[area]/[controller]")]
    public class ClientRedirectUriController : Controller
    {
        
        private IClientService _clientService;

        public ClientRedirectUriController(IClientService clientService)
        {
            this._clientService = clientService;
        }

        [HttpGet("[action]/{clientId}")]
        public async Task<IActionResult> Edit(string clientId)
        {
            Client client = await _clientService.Find(clientId);

            if(client == null)
            {
                ViewBag.Message = string.Format("The Auth Central Client with ClientId {0} could not be found.", clientId);
                return RedirectToAction("Edit");
            }

            var model = new ClientChildListContainer<string>()
            {
                ClientId = client.ClientId,
                ChildList = client.RedirectUris
            };
 
            model.ChildList.Add("");

            return View(model);
        }

        [HttpPost("[action]/{clientId}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string clientId, string redirectUri)
        {
            Client client = await _clientService.Find(clientId);

            if(client == null)
            {
                ViewBag.Message = string.Format("The Auth Central Client with ClientId {0} could not be found.", clientId);
                return RedirectToAction("Edit");
            }

            if(client.RedirectUris.Contains(redirectUri) )
            {
                client.RedirectUris.Remove(redirectUri);
                await _clientService.Save(client);
            }

            var model = new ClientChildListContainer<string>()
            {
                ClientId = client.ClientId,
                ChildList = client.RedirectUris
            };
 
            model.ChildList.Add("");

            return View("Edit", model);
        }

        [HttpPost("[action]/{clientId}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(string clientId, string originalRedirectUri, string redirectUri)
        {
            //TODO: validate??

            Client client = await _clientService.Find(clientId);

            if(client == null)
            {
                ViewBag.Message = string.Format("The Auth Central Client with ClientId {0} could not be found.", clientId);
            }

            // if things have changed
            if (originalRedirectUri != redirectUri)
            {
                bool saveRequired = false;

                if (!client.RedirectUris.Contains(redirectUri) && !String.IsNullOrWhiteSpace(redirectUri))
                {
                    var insertAt = client.RedirectUris.IndexOf(originalRedirectUri);
                    if (insertAt >= 0)
                    {
                        client.RedirectUris.Insert(insertAt, redirectUri);
                    }
                    else
                    {
                        client.RedirectUris.Add(redirectUri);
                    }
                    saveRequired = true;
                }

                if (client.RedirectUris.Contains(originalRedirectUri))
                {
                    client.RedirectUris.Remove(originalRedirectUri);
                    saveRequired = true;
                }

                if (saveRequired)
                {
                    await _clientService.Save(client);
                }
            }

            var model = new ClientChildListContainer<string>()
            {
                ClientId = client.ClientId,
                ChildList = client.RedirectUris
            };

            // cheating way to include an empty for on the view page
            model.ChildList.Add("");
            
            return View("Edit", model);
        }

    }
}

src/AuthCentral/Areas/Admin/Views/ClientRedirectUri/Edit.cshtml
@using Fsw.Enterprise.AuthCentral.Areas.Admin.Models
@model ClientChildListContainer<string>

@{
    Layout = "~/Areas/Admin/Views/Shared/_ClientAdminLayout.cshtml";
    ViewBag.Title = "View Client Redirect Uri's";
}

@for(var i=0; i < Model.ChildList.Count; i++)
{
    @using (Html.BeginForm("Save", "ClientRedirectUri", new { clientId = Model.ClientId, area = "Admin" }, FormMethod.Post, new { @id="edit-form-" + i, @class = "form-inline"} )) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => Model.ClientId)

        <div class="form-group">
           <div>
               <input type="hidden" class="form-control" id="originalRedirectUri_@i" name="originalRedirectUri" placeholder="http://new-app.fsw.com/" value="@Model.ChildList[i]">
               <input type="url" class="form-control" id="redirectUri_@i" name="redirectUri" placeholder="http://new-app.fsw.com/" value="@Model.ChildList[i]">
           </div>
        </div>
        <div class="form-group">
            <input type="button" value="Save" class="btn btn-success" onclick="javascript: document.forms['edit-form-@i'].submit();" />
            <input type="button" value="Delete" class="btn btn-warning" onclick="    javascript: document.forms['edit-form-@i'].action = '/admin/clientredirecturi/delete/@Model.ClientId'; document.forms['edit-form-@i'].submit();" />
       </div>
       <hr />
    }
}